apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::590183814659:role/eks-node-role
      username: system:node:{{EC2PrivateDNSName}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::590183814659:role/bastion-role
      username: bastion-role
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-13T12:03:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2919"
  uid: 12dc8345-cb64-4fd9-843a-9d878bfd7791