apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fortune-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: fortune-api
    spec:
      containers:
      - image: 590183814659.dkr.ecr.ap-south-1.amazonaws.com/fortune-api:latest
        name: fortune-api
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "8080"]
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - fortune-api
              topologyKey: "kubernetes.io/hostname"