apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fortune-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fortune-api
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60