apiVersion: v1
kind: Service
metadata:
  name: fortune-api
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: fortune-api
  type: LoadBalancer
